version: '3.4'

services:
  
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariaadmin
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: larapass
    volumes: 
      - ./mariadb/mysql:/var/lib/mysql
    ports: 
      - 4306:3306

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes: 
      - ./nginx/files:/etc/nginx
  
  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes: 
      - ../app:/var/www/htdocs

